openapi: 3.0.0
info:
  title: Product API
  description: API para la gestión de productos
  version: 1.0.0
paths:
  /api/products:
    get:
      summary: Obtener todos los productos
      description: Retorna una lista de todos los productos
      responses:
        '200':
          description: Lista de productos obtenida exitosamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
  /api/products/{id}:
    get:
      summary: Obtener producto por ID
      description: Retorna un producto específico
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID del producto
      responses:
        '200':
          description: Producto obtenido exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Producto no encontrado
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        price:
          type: number
        description:
          type: string